# Generated by Django 4.1.1 on 2022-09-10 18:53

from django.db import migrations, models
import other.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('percent_off', models.FloatField(validators=[other.validators.percent_validator], verbose_name='Percent off')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('percentage', models.FloatField(validators=[other.validators.percent_validator], verbose_name='Percent off')),
                ('stripe_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe ID')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
    ]
