# Generated by Django 4.1.1 on 2022-09-11 06:14

from django.db import migrations, models
import django.db.models.deletion
import other.validators


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('currency', models.CharField(blank=True, choices=[('usd', 'US dollars'), ('rub', 'Russian rubles')], max_length=3, null=True, verbose_name='Description')),
                ('amount_off', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount off')),
                ('percent_off', models.FloatField(validators=[other.validators.percent_validator], verbose_name='Percent off')),
                ('duration', models.CharField(choices=[('usd', 'US dollars'), ('rub', 'Russian rubles')], default='once', max_length=255, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Discount Coupon',
                'verbose_name_plural': 'Discount Coupons',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='other.discountcoupon', verbose_name='Купон')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
            },
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AddField(
            model_name='tax',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(choices=[('once', 'Once'), ('repeating', 'Repeating'), ('forever', 'Forever')], default='vat', max_length=9, verbose_name='Tax type'),
        ),
    ]
