# Generated by Django 4.1.1 on 2022-09-12 08:52

from django.db import migrations, models
import other.validators


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_discountcoupon_promocode_delete_discount_tax_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcoupon',
            name='amount_off',
        ),
        migrations.RemoveField(
            model_name='discountcoupon',
            name='currency',
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe ID'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe ID'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='duration',
            field=models.CharField(choices=[('once', 'Once'), ('forever', 'Forever')], default='once', max_length=255, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.FloatField(validators=[other.validators.percent_validator], verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(choices=[('vat', 'Vat'), ('sales_tax', 'Sales Tax')], default='vat', max_length=9, verbose_name='Tax type'),
        ),
    ]
