# Generated by Django 4.1.1 on 2022-09-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(default='usd', max_length=8, verbose_name='Currency'),
        ),
    ]
