# Generated by Django 4.1.1 on 2022-09-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='StripeId'),
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='StripeId'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'US dollars'), ('rub', 'Russian rubles')], default='usd', max_length=8, verbose_name='Currency'),
        ),
    ]
