# Generated by Django 4.1.1 on 2022-09-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_remove_discountcoupon_amount_off_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Order total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_with_promos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Order total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_with_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total with Taxes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order', verbose_name='Order'),
        ),
        migrations.CreateModel(
            name='DiscountToOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_bundles', to='other.discountcoupon', verbose_name='Coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_bundles', to='order.order', verbose_name='Order')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_bundles', to='other.promocode', verbose_name='Promo')),
            ],
        ),
    ]
